### PR TITLE
fix gh actions

### PR DESCRIPTION
**Pull request by zkamvar**
This reverts #75 and #76 and provides the fallback as proposed in #73

In the future, if there are failing feeds, use the `||` to shortcut on error
and report an `EXIT_STATUS` > 1 to the healthchecks.

- re-enable help-wanted and lessons in make
- allow help-wanted and lessons to error with status 2

### CODE REVIEW

**Comment by maneesha** [comment]
Thanks @zkamvar We know it's the lesson feeds that fail the most, but should we consider adding this line to each make line? 
I had started to look to see if there is a way to do this for all lines without adding it to each line.

**Comment by zkamvar** [comment]
> We know it's the lesson feeds that fail the most, but should we consider adding this line to each make line?
> I had started to look to see if there is a way to do this for all lines without adding it to each line.

Yes. I think that would be worthwhile.

**Comment by zkamvar** [comment]
> We know it's the lesson feeds that fail the most

It's the incubator feed that fails the most. The lessons feed has been consistent for the most part until now.

**Comment by zkamvar** [comment]
Unfortunately, this PR has reached its rate limit for the hour, so I will revisit this in an hour.

**Pull request merged**
