### PR TITLE
Sets up feeds for website stats

### PR DESCRIPTION
**Pull request by maneesha**
Our new website lets us publish quick stats. This feeds sets up data that the quick stats can be retrieved from.  

image

### CODE REVIEW

**Comment by froggleston** [comment]
Yes, keys should always be secret out of principle.

This seems to update when the site gets rebuilt. Would it be better to decouple the stats generation from the build cycle? Also, the bash script should have more error/exception handling in case the query returns unexpected data, no data, or that the API endpoint is not available.

**Comment by maneesha** [comment]
@froggleston  We have many feeds that are used to populate the websites (list of people like Instructors, Trainers, etc.), lists of member sites, and list of workshops.  So it would be fine for everything to update together.

I will add in some error handling (which most of our other feed scripts could use as well!). 

Should the key be added to AWS secrets?

**Comment by maneesha** [comment]
@froggleston this script now checks to see if the request returns `200`; if the returned body is not empty; and if the returned json has the key `query_result`.

**Review by froggleston — APPROVED** [review]
LGTM!

**Comment by maneesha** [comment]
Thanks @froggleston I don't want to merge this until we have the api key saved. Are secrets for feeds stored in AWS?

**Comment by froggleston** [comment]
Yes, we can either do it there, or store it in LastPass and use a local env file. I'd prefer the AWS SecretsManager solution as any kind of key rotation would automatically be handled.

**Comment by maneesha** [comment]
Secret `REDASH_KEY_QUERY713` has been added to this repo.

**Pull request merged**
